# Generated by Django 6.0.5 on 2026-05-07 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoColeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_residuo', models.CharField(choices=[('ELETRONICO', 'Eletrônicos e fios'), ('VIDRO', 'Garrafas e Vidros'), ('PLASTICO', 'Plásticos/PET'), ('OUTRO', 'Outros')], max_length=20)),
                ('endereco_descricao', models.TextField(help_text='Descição do Local ou Ponto de Referência')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('data_preferencial', models.DateField()),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ROTA', 'Em Rota'), ('CONCLUIDO', 'Concluído')], default='PENDENTE', max_length=15)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
