# Generated by Django 6.0.5 on 2026-05-07 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coleta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RotaOficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bairro', models.CharField(max_length=100)),
                ('dia_semana', models.CharField(max_length=100)),
                ('horario_estimado', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='solicitacaocoleta',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
