# Generated by Django 6.0.5 on 2026-05-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coleta', '0002_rotaoficial_solicitacaocoleta_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaocoleta',
            name='endereco_descricao',
            field=models.TextField(blank=True, help_text='Descrição do Local ou Ponto de Referência', null=True),
        ),
    ]
