# Generated by Django 6.0.5 on 2026-05-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coleta', '0003_alter_solicitacaocoleta_endereco_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaocoleta',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ROTA', 'Em Rota'), ('CONCLUIDO', 'Concluído'), ('NAO_COLETADO', 'Não Coletado / Ausente')], default='PENDENTE', max_length=15),
        ),
    ]
